### Tek satır for döngüsü (One-liner for)

In [ ]:
kelime = "Python"
harf_listesi = []

for harf in kelime:
    harf_listesi.append(harf)
    
print(harf_listesi)

In [ ]:
harf_listesi = [harf for harf in "Python"]

### Tek satır if (One-liner if)

In [ ]:
koşul = True

if koşul:
    kelime = "Elma"
else:
    kelime = "Armut"

In [ ]:
kelime = "Elma" if koşul else "Armut"

### Tek satır fonksiyon Lambda (One-liner function Lambda)

In [7]:
kare_al = lambda x: x**2
kare_al(5)

25

### map, reduce, filter, zip fonksiyonları

In [13]:
sayılar = [1, 2, 3, 4, 5, 6, 7]
sayıların_kareleri = []

for sayı in sayılar:
    sayıların_kareleri.append(sayı**2)
sayıların_kareleri

[1, 4, 9, 16, 25, 36, 49]

In [16]:
sayıların_kareleri =  list(map(kare_al, sayılar))
print(sayıların_kareleri)

for sayı in sayıların_kareleri:
    print(sayı)


[1, 4, 9, 16, 25, 36, 49]
1
4
9
16
25
36
49


In [17]:
from functools import reduce

sayılar = [1, 6, 3, 7, 10, 0]
print(reduce(lambda x,y: x if x > y else y, sayılar))

10


In [20]:
def beşten_uzun(kelime):
    if len(kelime) > 5:
        return True
    else:
        return False
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']
uzun_isimler = list(filter(beşten_uzun, isimler))
print(uzun_isimler)

for isim in uzun_isimler:
    print(isim)


['Necati', 'Mehmet']
Necati
Mehmet


In [ ]:
sayılar = [0, 1, 2, 3, 4, 5]
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']

for i in range(len(sayılar)):
    print(sayılar[i], isimler[i])
    
"""
for i in zip(sayılar, isimler):
    print(i)
"""

### Assert anahtar kelimesi ( Assert keyword )

In [ ]:
yaş = input("Yaşınız:")
assert int(yaş) >= 0, "Yaşınız negatif olamaz"

### Üreteçler (Generators)

In [21]:
def generator():
    i = 1
    print('Öncelikle bu basıldı')
    yield i

    i += 1
    print('Sonra bu')
    yield i

for eleman in generator():
    print("For döngüsü içinde:", eleman)
#print(next())

Öncelikle bu basıldı
For döngüsü içinde: 1
Sonra bu
For döngüsü içinde: 2


In [22]:
a = 5

def outer():
    a = 3
    def inner():
        nonlocal a
        a += 5
        print("inner fonksiyon:", a)
    print("outer fonksiyon:", a)
    return inner()

outer()
print("global:", a)

outer fonksiyon: 3
inner fonksiyon: 8
global: 5


In [23]:
from datetime import datetime

def show_time(func):
    def wrapper():
        print("Time:", datetime.now().time())
        func()
    return wrapper

@show_time
def say_hi():
    print("Hi!")

@show_time
def say_bye():
    print("Bye!")
    
say_hi()
say_bye()

Time: 01:09:14.182521
Hi!
Time: 01:09:14.182521
Bye!


# Numpy

![Scalar Vector Matrix Tensor](https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)

In [25]:
import numpy as np

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60])
print(type(a))
print(a.shape)

In [ ]:
a[2]

In [ ]:
a[2] *= 2
print(a[2])

In [ ]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(b)
print(b.shape)
print(b.dtype)

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60])
np.sin(a)

In [ ]:
np.cos(a)

In [ ]:
np.log(a)

In [ ]:
np.exp(a)

In [ ]:
np.max(a)

In [ ]:
np.min(a)

In [ ]:
np.argmax(a)

In [ ]:
np.mean(a)

In [ ]:
np.median(a)

In [ ]:
np.std(a)

In [ ]:
# axis=1 => Row
# axis=0 => Column
np.sum(b, axis=1)

In [ ]:
zeros = np.zeros((3, 3))
print(zeros)

In [ ]:
ones = np.ones((3, 3))
print(ones)

In [ ]:
full = np.full((3, 3), 5)
print(full)

In [ ]:
eye = np.eye(5)
print(eye)

In [ ]:
arange = np.arange(7)
print(arange)

arange = np.arange(0, 10, 2)
print(arange)

In [ ]:
random = np.random.random((3, 3))
print(random)

In [ ]:
arr = np.random.randint(20, size=(5, 5))
print(arr)

In [ ]:
arr[2, 1]

In [ ]:
zeros

In [ ]:
eye*6

In [ ]:
arr == 4

In [ ]:
np.where(arr == 4)

In [ ]:
np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]).reshape(4, 3)

In [ ]:
c = np.random.randint(10, size=(3, 3))
print(c)
c_inv = np.linalg.inv(c)
print(c_inv)

## İç Çarpım (Dot product)
![Dot product](https://lh3.googleusercontent.com/proxy/cTFYdypenGiCKxczG4R2oroQUAQomOw0JxklR8stnaJhufGF9TbfWeJflDKnvA9w1CZoNJC9S3MKW1KIaX_OS2Xl6D9ALXK9RVgYWf-3Z_9RrAj3UQ)

credit: http://hyperphysics.phy-astr.gsu.edu/hbase/vsca.html

In [26]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a.shape)

(2, 3)


In [27]:
b = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
print(a.shape)

(2, 3)


In [37]:
axb = np.dot(a, b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [29]:
(b.T).shape

(3, 2)

In [36]:
a,b.T

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]))

In [30]:
axb = np.dot(a, b.T)
print(axb)
print(axb.shape)

[[ 50  68]
 [122 167]]
(2, 2)
