In [1]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(array.shape)

(15,)


In [2]:
array.ndim

1

In [9]:
a = array.reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
print("shape: ", a.shape)
print("dimensions: ", a.ndim)
print("data type: ", a.dtype.name)

shape:  (3, 5)
dimensions:  2
data type:  int32


In [7]:
array.dtype.name

'int32'

In [17]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.empty((4,4))

array([[6.23042070e-307, 1.89146896e-307, 1.37961302e-306,
        1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306],
       [2.31420176e-306, 1.86918699e-306, 1.69120281e-306,
        1.33511969e-306],
       [1.33511018e-306, 7.56599807e-307, 8.34451503e-308,
        2.22507386e-306]])

In [25]:
np.linspace(10,50,20) #10'dan 50'ye kadar 20 tane sayı. 50 dahil.

array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
       20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
       31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
       41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ])

In [28]:
a = np.array([[1,2,3],[4,5,6]])

b = np.array([[1,2,3],[4,5,6]])

a.dot(b.T)

array([[14, 32],
       [32, 77]])