### **Neden NumPy**

In [1]:
a = [1,2,3,4]
b = [2,3,4,5]
a
b #sadece en sona ne yazdiysak onu yazdirir.

[2, 3, 4, 5]

In [9]:
import numpy as np

In [11]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5]) #listeleri numpy'da array olarak tanimliyoruz.

In [12]:
a*b #uzun uzun islemlere gerek kalmadan listeleri birbiri ile carpar.

array([ 2,  6, 12, 20])

## **NumPy Array'i Oluşturmak**

In [1]:
import numpy as np

In [2]:
 np.array([1,2,3,4,5]) #array olusturma

array([1, 2, 3, 4, 5])

In [4]:
 a = np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([3.14,4,2,1,13]) #float ve int karisik array

array([ 3.14,  4.  ,  2.  ,  1.  , 13.  ])

Veri saklarken sadece bir veri tipi tutabilmek için bütün sayıları ondalıklı bir değere çevirdi.

In [7]:
np.array([3.14,4,2,1,13], dtype="int") #Veri tipini kendimiz belirledik.

array([ 3,  4,  2,  1, 13])

 ## **Sıfırdan Array Oluşturma**

In [1]:
import numpy as np

In [3]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3,5) , dtype=int) #1'lerden olusan 3'e 5'lik 2 boyutlu array(matris)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.full((4,5) , 3) #3'lerden olusan 4x5'lik matris

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [8]:
np.arange(0,31,3) #0'dan 31'e kadar 3'er 3'er artan dogrusal dizi.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [9]:
np.linspace(0,1,10) #0 ile 1 arasinda 10 tane sayi olustur.

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [10]:
np.random.normal(10, 4, (3,4)) #ortalamasi=10, standart sapmasi=4 olan 3x4'luk matris

array([[11.58826043, 11.68947875, 14.08713841, 10.49055712],
       [ 7.37205302, 11.91140801, 11.31641312, 12.05287956],
       [ 3.44476323,  9.28895348,  8.88684624,  6.07701004]])

In [11]:
np.random.randint(0, 10, (3,3)) #0 ile 10 araliginde rastgele int degerlerden 3x3'luk matris

array([[8, 4, 3],
       [0, 3, 7],
       [1, 2, 3]])

## **NumPy Array Özellikleri**

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [1]:
import numpy as np

In [4]:
np.random.randint(10, size = 10)

array([3, 3, 9, 6, 7, 8, 5, 1, 6, 1])

In [5]:
a = np.random.randint(10, size = 10)

In [6]:
a.ndim #boyut sayisi-- Tek boyutlu bir array oldugundan 1 gelecek.

1

In [7]:
a.shape #boyut bilgisi-- Elimizdeki array tek boyutlu oldugundan sadece tek boyutunun bilgisini verecek.

(10,)

In [9]:
a.size #eleman sayisi

10

In [10]:
 a.dtype #array'in veri tipi

dtype('int32')

**İki boyutlu array oluşturalım**

In [11]:
b = np.random.randint(10, size = (3,5)) #3x5'lik 0 ile 10 arasindaki degerlerden olusan matris.

In [12]:
b

array([[4, 8, 4, 6, 0],
       [9, 6, 3, 4, 0],
       [8, 8, 4, 5, 7]])

In [13]:
b.ndim

2

In [14]:
b.shape

(3, 5)

In [15]:
b.size

15

In [16]:
b.dtype

dtype('int32')