## **Pandas Serisi Oluşturmak**

Pandas içerisinde yer alan veri tipleri değerleri, indeksleri ile beraber tutar.

In [1]:
import pandas as pd

In [2]:
pd.Series([10,88,3,4,5]) #pandas serisi olusturmak.

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [3]:
 seri = pd.Series([10,88,3,4,5])

In [4]:
type(seri)

pandas.core.series.Series

In [5]:
seri.axes #Serinin index bilgisine ulasiriz.

[RangeIndex(start=0, stop=5, step=1)]

In [6]:
seri.dtype

dtype('int64')

In [9]:
seri.size #eleman sayisi

5

In [10]:
seri.ndim #boyutu

1

In [11]:
seri.values #vektor formunda sadece degerlere ulasiriz.

array([10, 88,  3,  4,  5], dtype=int64)

In [7]:
seri.head() #ilk 5 eleman

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [8]:
seri.head(3) #ilk 3 eleman

0    10
1    88
2     3
dtype: int64

In [9]:
seri.tail(3) #son 3 eleman

2    3
3    4
4    5
dtype: int64

**Index İsimlendirmesi**

In [10]:
pd.Series([23,24,25,26,27], index = [2,4,6,8,10])

2     23
4     24
6     25
8     26
10    27
dtype: int64

In [11]:
seri = pd.Series([23,24,25,26,27], index = ["a","b","c","d","e"])

In [13]:
seri

a    23
b    24
c    25
d    26
e    27
dtype: int64

In [14]:
seri["a"] #elemana erisme

23

In [15]:
seri["a":"c"] #serilerde slice islemi

a    23
b    24
c    25
dtype: int64

**Sözlük üzerinden seri oluşturmak**

In [16]:
sozluk={"reg":10, "log":11, "cart":12}

In [18]:
seri = pd.Series(sozluk)

In [19]:
seri

reg     10
log     11
cart    12
dtype: int64

**İki Seriyi Birleştirerek Seri Oluşturma**

In [20]:
pd.concat([seri, seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

## **Eleman İşlemleri**

In [23]:
import numpy as np
a = np.array([15,233,34,52,64])
seri = pd.Series(a) #NumPy Array'i uzerinden seri olusturalim
seri

0     15
1    233
2     34
3     52
4     64
dtype: int32

In [24]:
seri[0] #0 indexli eleman

15

In [25]:
seri[0:3] #3'e kadar olan elemanlar

0     15
1    233
2     34
dtype: int32

In [27]:
seri = pd.Series([133,244,355,467,234], index = ["reg","log","cart","pcv","rf"])
seri

reg     133
log     244
cart    355
pcv     467
rf      234
dtype: int64

In [29]:
seri.index #sadece indexler

Index(['reg', 'log', 'cart', 'pcv', 'rf'], dtype='object')

In [30]:
seri.keys #seri'nin key'lerini gosterir

<bound method Series.keys of reg     133
log     244
cart    355
pcv     467
rf      234
dtype: int64>

In [31]:
list(seri.items()) #key degerine karsilik gelen value'lari bir araya getirerek list olusturur.

[('reg', 133), ('log', 244), ('cart', 355), ('pcv', 467), ('rf', 234)]

In [32]:
seri.values #seri'nin sadece degerlerini gosterir

array([133, 244, 355, 467, 234], dtype=int64)

**Eleman Sorgulama**

In [33]:
"reg" in seri

True

In [34]:
"a" in seri

False

In [35]:
seri["reg"]

133

**Fancy Eleman**

In [37]:
seri[["rf","reg"]] #fancy ile eleman secme

rf     234
reg    133
dtype: int64

**Eleman Değiştirme**

In [39]:
seri["reg"] = 111
seri #atama yontemi ile tekrardan eleman atayabiliriz.

reg     111
log     244
cart    355
pcv     467
rf      234
dtype: int64

## **Pandas DataFrame Oluşturma**

Pandas DataFrame yapısal bir veri tipidir.

In [2]:
import pandas as pd
l = [5,12,37,62,14] #list olusturduk
l

[5, 12, 37, 62, 14]

pd.DataFrame(l, columns = ["degisken_ismi"]) #DataFrame olusturma

In [5]:
import numpy as np
m = np.arange(1,10).reshape(3,3)
m #3x3'luk bir matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
pd.DataFrame(m, columns=["var1","var2","var3"]) #2 boyutlu DataFrame

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

**Yapay zeka ve Veri Biliminde en çok kullanacağımız veri tipi DataFrame'dir.**

**DataFrame İsimlendirme**

In [7]:
df = pd.DataFrame(m, columns=["var1","var2","var3"])
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [8]:
df.columns = ("col1","col2","col3") #Sutunlari yeniden isimlendirme
df

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

**DataFrame Özellikleri**

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.axes #Satir ve sutun bilgisi

[RangeIndex(start=0, stop=3, step=1),
 Index(['col1', 'col2', 'col3'], dtype='object')]

In [11]:
df.shape #boyut bilgisi

(3, 3)

In [12]:
df.ndim #boyut sayisi

2

In [13]:
df.size #eleman sayisi

9

In [14]:
df.values #DataFrame tipindeki veri yapisinin icersinden
          #Degerleri array tipinde aliyor.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
type(df.values)

numpy.ndarray

In [17]:
df.tail(1) #sondan 1. index

col1  col2  col3
2     7     8     9

Diğer veri tiplerinde veri oluşturmak için çeşitli formatlar kullandık.<br>
Örneğin; NumPy array'i üzerinden oluşturduk list üzerinden oluşturduk ve buna<br>
benzer farklı formatlardan oluşturduk. Bu işlemler DataFrame için de geçerlidir.

In [18]:
a = np.array([1,2,3,4,5])

In [21]:
pd.DataFrame(a, columns = ["deg1"]) #numpy array'i ile df olusturduk.

deg1
0     1
1     2
2     3
3     4
4     5

## **DataFrame Eleman İşlemleri**

In [1]:
import numpy as np
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)

In [2]:
sozluk={"var1":s1,"var2":s2,"var3":s3} #array'lerden sozluk
sozluk

{'var1': array([0, 6, 2, 5, 7]),
 'var2': array([2, 1, 7, 6, 2]),
 'var3': array([3, 2, 3, 2, 3])}

In [4]:
import pandas as pd
df = pd.DataFrame(sozluk) #sozluk'den df
df

var1  var2  var3
0     0     2     3
1     6     1     2
2     2     7     3
3     5     6     2
4     7     2     3

In [7]:
df[0:2] #0'dan 2'ye kadar

var1  var2  var3
0     0     2     3
1     6     1     2

In [8]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
df.index = ["a","b","c","d","e"]

In [11]:
df

var1  var2  var3
a     0     2     3
b     6     1     2
c     2     7     3
d     5     6     2
e     7     2     3

In [12]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [15]:
df["a":"c"]

var1  var2  var3
a     0     2     3
b     6     1     2
c     2     7     3

**Eleman Silme**

In [22]:
df.drop("a", axis=0) #0 ekseninden "a" indexli satiri sil.

var1  var2  var3
b     6     1     2
c     2     7     3
d     5     6     2
e     7     2     3

In [17]:
df #sildi ancak kaydetmedi.

var1  var2  var3
a     0     2     3
b     6     1     2
c     2     7     3
d     5     6     2
e     7     2     3

In [23]:
df.drop("a", axis=0, inplace=True) #inplace argumani kalici olsun mu? anlamındadir.

In [24]:
df #kalici olarak silindi.

var1  var2  var3
b     6     1     2
c     2     7     3
d     5     6     2
e     7     2     3

**Fancy**

In [26]:
l = ["c","e"]

In [27]:
df.drop(l, axis=0) #c ve e silindi

var1  var2  var3
b     6     1     2
d     5     6     2

**Degiskenler icin**

In [31]:
df

var1  var2  var3
b     6     1     2
c     2     7     3
d     5     6     2
e     7     2     3

In [32]:
"var1" in df

True

In [35]:
l = ["var1","var4","var2"]

In [37]:
for i in l:
    print(i in df) 

True
False
True


Bir değişken oluşturmak isteyelim fakat bu değişkenimizi DataFrame içinde <br>var olan değişkenlerden yapmak istediğimizi düşünelim.

In [38]:
df

var1  var2  var3
b     6     1     2
c     2     7     3
d     5     6     2
e     7     2     3

In [39]:
df["var4"] = df["var1"] / df["var2"]

In [40]:
df

var1  var2  var3      var4
b     6     1     2  6.000000
c     2     7     3  0.285714
d     5     6     2  0.833333
e     7     2     3  3.500000

**Değişken Silme**

In [43]:
df

var1  var2  var3      var4
b     6     1     2  6.000000
c     2     7     3  0.285714
d     5     6     2  0.833333
e     7     2     3  3.500000

In [44]:
df.drop("var4", axis=1, inplace=True)
df

var1  var2  var3
b     6     1     2
c     2     7     3
d     5     6     2
e     7     2     3

In [47]:
l = ["var1","var2"]
df.drop(l, axis=1)  #Fancy ile silme

var3
b     2
c     3
d     2
e     3

## **Gözlem ve Değişken Seçimi**